<?php
/**
 * Created by PhpStorm.
 * User: roberto
 * Date: 19/06/17
 * Time: 05:29
 */

namespace AppBundle\Form;

use AppBundle\Entity\Fila;
use AppBundle\Entity\Setores;
use Doctrine\DBAL\Types\TextType;
use function Sodium\add;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\ChoiceType;
use Symfony\Component\Form\Extension\Core\Type\DateType;
use Symfony\Component\Form\Extension\Core\Type\TextareaType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;


class DevolverChamadoForm extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        parent::buildForm($builder, $options); // TODO: Change the autogenerated stub
        $builder
            ->add("Nome", \Symfony\Component\Form\Extension\Core\Type\TextType::class, [
                'disabled' => true
            ])
            ->add("Descricao", TextareaType::class, [
                'disabled' => true
            ])
            ->add("Setor", EntityType::class, [
                'class' => Setores::class,
                'placeholder' => 'Escolha o setor de destino',
                'disabled' => true
            ])
            ->add("Prioridade", ChoiceType::class, ['choices' => array(
                'Urgente' => 'urgente',
                'Média Urgencia' => 'mediaUrgencia',
                'Baixa Urgencia' => 'baixaUrgencia',

            ),'disabled' => true])
            ->add("Fila", EntityType::class, [
                'class' => Fila::class,
                'placeholder' => 'Escolha a fila',
                'disabled' => true
            ])
            ->add('dataLimite', DateType::class, [
                'widget' => 'single_text',
                'attr' => ['class' => 'js-datepicker'],
                'html5' => false,
                'disabled' => true
            ])
            ->add('comentario', TextareaType::class);

    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults(['data_class' => "AppBundle\Entity\Chamados"]);
    }
}

