<?php
/**
 * Created by PhpStorm.
 * User: roberto
 * Date: 19/06/17
 * Time: 02:23
 */

namespace AppBundle\Form;

use AppBundle\Entity\Fila;
use Doctrine\DBAL\Types\TextType;
use function Sodium\add;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class novaFilaForm extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        parent::buildForm($builder, $options); // TODO: Change the autogenerated stub
        $builder
            ->add('nome', \Symfony\Component\Form\Extension\Core\Type\TextType::class);
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        parent::configureOptions($resolver); // TODO: Change the autogenerated stub
        $resolver->setDefaults(['data_class' => 'AppBundle\Entity\Fila']);
    }
}