<?php
/**
 * Created by PhpStorm.
 * User: roberto
 * Date: 22/05/17
 * Time: 17:15
 */

namespace AppBundle\Form;

use Doctrine\DBAL\Types\TextType;
use function Sodium\add;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\ChoiceType;
use Symfony\Component\Form\Extension\Core\Type\DateType;
use Symfony\Component\Form\Extension\Core\Type\TextareaType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class novoChamadoForm extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        parent::buildForm($builder, $options); // TODO: Change the autogenerated stub
        $builder
            ->add("Motivo", \Symfony\Component\Form\Extension\Core\Type\TextType::class)
            ->add("Descricao", TextareaType::class)
            ->add("Setor")
            ->add("Prioridade")
            ->add("Fila")
            ->add("DataLimite", DateType::class, [
                'widget' => 'single_text',
                'attr' => ['js-datepicker'],

            ]);

    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults(['data_class' => "AppBundle\Entity\Chamados"]);
    }
}