<?php
/**
 * Created by PhpStorm.
 * User: roberto
 * Date: 22/05/17
 * Time: 17:15
 */

namespace AppBundle\Form;


use function Sodium\add;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class novoChamadoForm extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        parent::buildForm($builder, $options); // TODO: Change the autogenerated stub
        $builder
            ->add("Nome")
            ->add("Descricao")
            ->add("Setor")
            ->add("Prioridade");

    }

    public function configureOptions(OptionsResolver $resolver)
    {
        parent::configureOptions($resolver); // TODO: Change the autogenerated stub
    }
}